### PR TITLE
Upgrade pull-ws

### PR DESCRIPTION
**Pull request by dominictarr**
These changes are necessary after recent changes to https://github.com/pull-stream/pull-ws/pull/26

I also improved test coverage, reusing the same tests for net and ws. @mixmix

### CODE REVIEW

**Comment by dominictarr** [comment]
@christianbundy also this

**Comment by dominictarr** [comment]
@christianbundy I think maybe this just needs to be merged. check if the tests of sbot and multiserver still work when this is linked in.

**Comment by dominictarr** [comment]
if it does then hit merge

**Comment by christianbundy** [comment]
This branch isn't passing tests for me locally, and Travis is reporting the same problem. It seems to be hanging here:

```
# combined.ws, aborted

server error, from ws:::ffff:127.0.0.1~shs:

Error: stream ended with:0 but wanted:64

    at drain (/home/travis/build/ssbc/multiserver/node_modules/pull-reader/index.js:43:26)

    at /home/travis/build/ssbc/multiserver/node_modules/pull-reader/index.js:63:18

    at /home/travis/build/ssbc/multiserver/node_modules/pull-reader/index.js:20:7

    at WebSocket.<anonymous> (/home/travis/build/ssbc/multiserver/node_modules/pull-ws/source.js:40:7)

    at WebSocket.onClose (/home/travis/build/ssbc/multiserver/node_modules/ws/lib/WebSocket.js:446:14)

    at WebSocket.emit (events.js:203:15)

    at WebSocket.cleanupWebsocketResources (/home/travis/build/ssbc/multiserver/node_modules/ws/lib/WebSocket.js:950:8)

    at Socket.emit (events.js:203:15)

    at endReadableNT (_stream_readable.js:1129:12)

    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by arj03** [comment]
It works if you link in the [upgraded](https://github.com/pull-stream/pull-ws/pull/26) pull-ws

**Comment by arj03** [comment]
Merge with main. Waiting for [pull-ws](https://github.com/pull-stream/pull-ws/pull/26) to be merged to be able to move forward. After that is in, the tests for this should be working again.

**Comment by arj03** [comment]
It seems like pull-ws is dead. Nobody with commit access seems interested. I'm considering just forking it and using that for my projects, and update multiserver to use the fork. Any thoughts on this?

**Comment by christianbundy** [comment]
sounds great to me

**Comment by arj03** [comment]
Alright so I think this is ready. I forked pull-ws as [pull-websocket](https://github.com/arj03/pull-websocket) as and fixed the tests. With this I have had a quite stable room connection with patchwork. @cryptix shall we test rooms2 tomorrow? :)

**Comment by staltz** [comment]
Cool, I'd like to merge it but gotta fix some git conflicts first

**Comment by arj03** [comment]
The conflicts should be fixed, the only thing I'd maybe like to fix is this [line](https://github.com/ssb-js/multiserver/pull/50/files#diff-ddade62b8b88ae0c0ffea88390eb3b137a39dc9f0cc6e36336ada5579d77ad52R455). That test was not in the old code so I don't think it's a new problem.

**Comment by arj03** [comment]
Alrighty part2: I fixed the tests now as well (mainly in pull-websocket). When you call close on a server it will only stop accepting new connections, not actually kill existing. IIRC the argument for that is related to deadlocks and its a common gotcha.

**Comment by arj03** [comment]
Does your comment @staltz mean that you are okay if I merge this? :)

**Comment by staltz** [comment]
Yes!

**Pull request merged**
