### PR TITLE
Create test.md

### PR DESCRIPTION
**Pull request by staltz**
Trying to get CI to run just to see what happens

### CODE REVIEW

**Comment by staltz** [comment]
what's going on? :roll_eyes: 

Screenshot from 2020-12-21 11-10-06

**Comment by arj03** [comment]
Yeah I was wondering the same thing 👀

**Comment by arj03** [comment]
I looked at this for a bit. Maybe it's travis still blocking this somehow. It is enabled on the organization level. @christianbundy do you have any idea what is going on here?

**Comment by christianbundy** [comment]
My only hunch: Maybe `node.js.yml` isn't a valid workflow name? I'd use `node.yml` or `main.yml` or something without the extra suffix. The tests should've run in #65 though.

**Comment by arj03** [comment]
Testing something, I've tried disabling travis to see if that changes anything. The filename should work, it works in the other repos we have in ssb-ngi-pointer.

**Comment by arj03** [comment]
Ohhhhhhhhhhhhhh yes :-)

**Comment by arj03** [comment]
OMG, I thought this was going to be simple ;)

**Comment by staltz** [comment]
Looks painful :D

**Comment by staltz** [comment]
And yeah, that `master` and `main` thing, ouch

**Comment by arj03** [comment]
Yeah, almost there but now I'm out of mana

**Comment by staltz** [comment]
So, turns out there's no node 8.x in GH actions? I guess that's not a big deal as node 8 isn't anymore supported officially.

**Comment by arj03** [comment]
Closed in favor of #67

**Pull request closed without merging**
